import Footer from './component/footer'
import Hero from './component/hero'
import Navbar from './component/navbar'

import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'sajjad-portfolio',
  description: 'Generated by Muhammad Sajjad Afzal',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
